### PR TITLE
Feature/dependency update

### PR DESCRIPTION
**Pull request by rstiller**
changes:
- updated dependencies
- added ava config in package.json
- pinned versions in package.json
- adapted new openpgp version in pgpVerifier, -signer & keybaseVerifier
- removed unused imports from files
- added .editorconfig file
- tsconfig ensures LR instead of CRLF in javascript files
- removed normalized script and @dpwolfe/dos2unix dependency
- packed packge-file only contains signature.json and dist folder (and readme + package.json)

### CODE REVIEW

**Comment by hach-que** [comment]
I had a look at this, but it looks like `pkgsign` can't verify itself after these changes are applied. I've added a "sign & verify" step to `yarn test` to easily pick up on this.

In addition, I restored the normalize script. It's required when developing on Windows (which I do).

**Comment by rstiller** [comment]
I'll investigate what's going on there - `yarn test` fails at the end for me.  
I updated my workspace with your changes and will ping you when I resolved the issue.

**Comment by rstiller** [comment]
@hach-que updated the pull-request:
- introduced '--allow-unsigned-packages' option for verify command only applicable for verifying directory
- rebased the branch with dev branch

**Comment by hach-que** [comment]
This is still failing for me, even immediately after `git clean`. I'm running Windows, so if you're not developing on Windows you might want to give that a shot to debug the issue (`\r\n` -> `\n` normalization is an issue).

```
jrhod@THANOS C:\Users\jrhod\Documents\Projects\pkgsign
$ git clean -xdff
Removing node_modules/

jrhod@THANOS C:\Users\jrhod\Documents\Projects\pkgsign
$ yarn
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 11.94s.

jrhod@THANOS C:\Users\jrhod\Documents\Projects\pkgsign
$ yarn test
yarn run v1.15.2
$ ava test/*.ts && yarn build && node dist/index.js sign . && node dist/index.js verify . --allow-unsigned-packages

- building file list...
\ building file list...
| building file list...
/ obtaining identity...
- creating signature...
\ creating deterministic string...
signing deterministic string...
signing with private pgp key...
obtaining identity...
creating signature...
| creating deterministic string...
signing deterministic string...
signing with private pgp key...
| signature.json has been created in package directory
/ signature.json has been created in package directory
- WARNING: package 'signature-packageJson-omits-npm-on-verify' is either published and/or installed with npm - falling back to limited verification of package.json
\ WARNING: package 'regular-pkg-packageJson-modified' is either published and/or installed with npm - falling back to limited verification of package.json
| WARNING: package 'regular-pkg' is either published and/or installed with npm - falling back to limited verification of package.json
\ signature has packageJson entry present
/ signature packageJson omits NPM fields on verify

  3 passedcreating signature...
creating deterministic string...
signing deterministic string...
signing with private pgp key...
package verification summary:
0 compromised
0 unsigned
/ signature packageJson omits NPM fields on verify
- signature packageJson omits NPM fields on verify

  3 passed1 compromised
0 unsigned
0 untrusted
\ signature packageJson omits NPM fields on verify
/ check signature of package

  4 passed0 compromised
0 unsigned
- check signature of package

  4 passedpackage verification summary:
1 compromised
0 unsigned
\ check signature of package

/ verify valid signature of installed package
- verify valid signature of installed package

  5 passed0 unsigned
0 untrusted
1 trusted
package verification summary:
1 compromised
0 unsigned
| fail verification on manipulated package content

  6 passedpackage verification summary:
1 compromised
0 unsigned

  6 tests passed

$ yarn clean && tsc
$ rimraf dist
building file list...
obtaining identity...
determining your keybase username...
creating signature...
creating deterministic string...
signing deterministic string...
requesting keybase pgp sign deterministic signature...
(you may receive an interactive prompt from keybase)
signature.json has been created in package directory
fetching public keys of user hachque...
package verification summary:
1 compromised
515 unsigned
0 untrusted
0 trusted
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

jrhod@THANOS C:\Users\jrhod\Documents\Projects\pkgsign
$
```

**Comment by rstiller** [comment]
hhmmm ... OK will dig deeper into the issue. Thanks for testing.

**Comment by rstiller** [comment]
Sorry for the long delay.

Unfortunately I can't reproduce the error on my machine:

```shell
PS C:\git\pkgsign> git clean -xdff
Removing node_modules/
Removing test/signature-has-packageJson-entry-present/signature.json
Removing test/signature-packageJson-omits-npm-on-sign/signature.json
PS C:\git\pkgsign> yarn
yarn install v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...

Done in 6.39s.
PS C:\git\pkgsign> yarn test
yarn run v1.16.0
$ ava test/*.ts && yarn build && node dist/index.js sign . && node dist/index.js verify . --allow-unsigned-packages

| building file list...
/ building file list...
- building file list...
\ obtaining identity...
| creating signature...
/ creating deterministic string...
- signing deterministic string...
signing with private pgp key...
\ obtaining identity...
creating signature...
creating deterministic string...
signing deterministic string...
| signing with private pgp key...
| WARNING: package 'signature-packageJson-omits-npm-on-verify' is either published and/or installed with npm - falling back to limited verification of package.json
/ signature.json has been created in package directory
- signature.json has been created in package directory
\ WARNING: package 'regular-pkg' is either published and/or installed with npm - falling back to limited verification of package.json
| WARNING: package 'regular-pkg-packageJson-modified' is either published and/or installed with npm - falling back to limited verification of package.json
\ signature packageJson omits NPM fields on sign

  2 passedobtaining identity...
creating signature...
creating deterministic string...
signing deterministic string...
signing with private pgp key...
package verification summary:
0 compromised
- signature packageJson omits NPM fields on verify
| signature packageJson omits NPM fields on verify

/ signature packageJson omits NPM fields on verify

  3 passed0 unsigned
- signature packageJson omits NPM fields on verify
\ signature packageJson omits NPM fields on verify

  3 passedpackage verification summary:
0 compromised
0 unsigned
/ check signature of package
- check signature of package

  4 passed1 compromised
0 unsigned
\ check signature of package
/ verify valid signature of installed package

  5 passed0 compromised
0 unsigned
- verify valid signature of installed package
\ verify valid signature of installed package

  5 passedpackage verification summary:
1 compromised
0 unsigned
| verify valid signature of installed package

- fail verification on manipulated package content

  6 passed0 unsigned

  6 tests passed

$ yarn clean && tsc
$ rimraf dist
building file list...
obtaining identity...
determining your keybase username...
creating signature...
creating deterministic string...
signing deterministic string...
requesting keybase pgp sign deterministic signature...
(you may receive an interactive prompt from keybase)
signature.json has been created in package directory
package verification summary:
0 compromised
515 unsigned
0 untrusted
1 trusted
Done in 23.19s.
PS C:\git\pkgsign>
```

One noticeable difference in the output is `fetching public keys of user hachque...` at the end.
Can I convince you to put some `console.log` statements in the code to see where and what is not working as expected?

**Comment by hach-que** [comment]
I ended up upgrading the packages and refactoring the code base for `0.2.0`.

**Pull request closed without merging**
