### PR TITLE
package json properties verification

### PR DESCRIPTION
**Pull request by rstiller**
What changed:
- sign & verify only properties the package onwer set explicitly in package.json
    - excluding properties starting with underscore (`_`)
    - still able to verify `packageJson/v1alpha1`
- removed unused imports
- added some test packages to verify signing & verification
- added some docs to explain why package.json needs special treatment

### CODE REVIEW

**Comment by hach-que** [comment]
Thanks for this.

Now that NPM creates package-lock.json, can we use the presence of that file to enable this behavior? That way we remain entirely secure when the user is using Yarn, and only fallback to this less secure mode when we can't avoid it.

Since with this we'd be skipping cryptographic verification of some properties under NPM, I'd also like to warn people when this mode kicks in, advising them to use Yarn for increased security. The verify command should emit a warning to that effect.

**Comment by rstiller** [comment]
I was facing some problems when publishing a package (with npm):  

The property `gitHead` was added to the package.json after the signature was created using the prepublish script. Don't know if it is the same with yarn - will investigate.
I also witnessed npm changing / overwriting properties like repository (see README.md) - will investigate if yarn is doing so as well.

Using this method would require to have two packageJson entries right?
One for yarn users who can use `packageJson/v1alpha1` (primary) and another one for npm users using `packageJson/v1alpha2` (fallback)

**Comment by hach-que** [comment]
Yarn doesn't modify any files on publish. It leaves everything intact.

Yeah we'll need two entries. Though the NPM one should probably be called `npmPackageJson/v1alpha1` since it's not really a better version of `packageJson/v1alpha1`.

**Comment by rstiller** [comment]
OK, I'll update the pull-request accordingly.

**Comment by hach-que** [comment]
Thanks!

**Comment by hach-que** [comment]
Hmm, actually it seems that this issue was already resolved in `0.2.0-alpha.4`. If you try installing pkgsign as outlined here: https://github.com/RedpointGames/pkgsign/issues/4#issuecomment-384734418, does it resolve the issues you were having?

That said, the way that's implemented it doesn't verify those fields for Yarn, and I think we're much better off with what's outlined here, in that only NPM should use a less secure mode of verification. I think at the time, `package-lock.json` wasn't a thing, so we couldn't rely on it's presence.

**Comment by rstiller** [comment]
Yes, I read the commit history and the issue history to be sure not to raise a pull request unnecessarily. I installed the version from the 0.2.0-alpha.4 branch, signed the package (https://github.com/rstiller/slf4ts/tree/master/packages/slf4ts-api), published it and installed it in an other project. The verification failed on the modified package.json (`gitHead` property was added and repository property was modified).

**Comment by hach-que** [comment]
Ah yes, I can see now this merge is against `dev` not `master` (the target branch doesn't show up on the mobile UI). All good.

**Comment by rstiller** [comment]
@hach-que ping: updated the pull request
What do you think: Can we remove the code from `SignaturePackageJsonEntry` that strips `generatedNpmKeys` from the package.json object and making it a very strict verification instead?

The current version of this PR skips the verification with `SignaturePackageJsonEntry` (printing a warning in the console) either if npm was used to install or publish the package. So if we install and publish with yarn only the strict verification should pass (as well as the npm compatible verification).

**Comment by hach-que** [comment]
Yup, we can remove the `generatedNpmKeys` and make it very strict verification now that we have a separate fallback for NPM users.

**Comment by rstiller** [comment]
OK, I'll update the PR and ping you when I'm finished with it

**Comment by hach-que** [comment]
Thanks.

**Comment by rstiller** [comment]
@hach-que ping: updated the pull request
- removed restriction on fields when doing packageJson/v1alpha1 check
- added tests for yarn-installed packages

**Comment by rstiller** [comment]
@hach-que did you had time to review the pull-request?

**Comment by hach-que** [comment]
Sorry, I've been moving apartments this weekend and I'm flat out!

I'll try to have a look at this next weekend.

**Comment by rstiller** [comment]
@hach-que Can you give an estimation when you have time to review the pull request?

**Comment by hach-que** [comment]
I'll have a look at this tonight.

**Review by hach-que — APPROVED** [review]

**Pull request merged**
